import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* ✅ Fixed Header */}
        <header className="fixed top-0 left-0 w-full bg-gradient-to-r from-blue-500 to-purple-600 shadow-md z-50">
          <nav className="max-w-7xl mx-auto flex justify-between items-center px-6 py-4">
            
            {/* Logo */}
            <h1 className="font-bold text-lg">MyApp</h1>

            {/* Nav Links */}
            <ul className="flex gap-6">
              <li>
                <Link  href="/translation" className="text-blue-200 hover:text-white">
                  Translation
                </Link>
              </li>
              <li>
                <Link href="/customer-support-representative" className="text-blue-200 hover:text-white">
                  Customer Support Representative
                </Link>
              </li>
              <li>
                <Link href="/chatbot" className="text-blue-200 hover:text-white">
                  Chatbot
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-blue-200 hover:text-white">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </header>

        {/* ✅ Main Content (push down because header is fixed) */}
        <main className="flex-1 pt-20">
          {children}
        </main>

      </body>
    </html>
  );
}